// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gin_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.25/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.25/cocotola-auth/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGuestUsecase creates a new instance of MockGuestUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuestUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuestUsecase {
	mock := &MockGuestUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGuestUsecase is an autogenerated mock type for the GuestUsecase type
type MockGuestUsecase struct {
	mock.Mock
}

type MockGuestUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuestUsecase) EXPECT() *MockGuestUsecase_Expecter {
	return &MockGuestUsecase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockGuestUsecase
func (_mock *MockGuestUsecase) Authenticate(ctx context.Context, organizationName string) (*service.AuthTokenSet, error) {
	ret := _mock.Called(ctx, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *service.AuthTokenSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.AuthTokenSet, error)); ok {
		return returnFunc(ctx, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.AuthTokenSet); ok {
		r0 = returnFunc(ctx, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AuthTokenSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuestUsecase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockGuestUsecase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationName string
func (_e *MockGuestUsecase_Expecter) Authenticate(ctx interface{}, organizationName interface{}) *MockGuestUsecase_Authenticate_Call {
	return &MockGuestUsecase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, organizationName)}
}

func (_c *MockGuestUsecase_Authenticate_Call) Run(run func(ctx context.Context, organizationName string)) *MockGuestUsecase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuestUsecase_Authenticate_Call) Return(authTokenSet *service.AuthTokenSet, err error) *MockGuestUsecase_Authenticate_Call {
	_c.Call.Return(authTokenSet, err)
	return _c
}

func (_c *MockGuestUsecase_Authenticate_Call) RunAndReturn(run func(ctx context.Context, organizationName string) (*service.AuthTokenSet, error)) *MockGuestUsecase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordUsecase creates a new instance of MockPasswordUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordUsecase {
	mock := &MockPasswordUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordUsecase is an autogenerated mock type for the PasswordUsecase type
type MockPasswordUsecase struct {
	mock.Mock
}

type MockPasswordUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordUsecase) EXPECT() *MockPasswordUsecase_Expecter {
	return &MockPasswordUsecase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockPasswordUsecase
func (_mock *MockPasswordUsecase) Authenticate(ctx context.Context, loginID string, password string, organizationName string) (*service.AuthTokenSet, error) {
	ret := _mock.Called(ctx, loginID, password, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *service.AuthTokenSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*service.AuthTokenSet, error)); ok {
		return returnFunc(ctx, loginID, password, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *service.AuthTokenSet); ok {
		r0 = returnFunc(ctx, loginID, password, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AuthTokenSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, loginID, password, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordUsecase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockPasswordUsecase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - loginID string
//   - password string
//   - organizationName string
func (_e *MockPasswordUsecase_Expecter) Authenticate(ctx interface{}, loginID interface{}, password interface{}, organizationName interface{}) *MockPasswordUsecase_Authenticate_Call {
	return &MockPasswordUsecase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, loginID, password, organizationName)}
}

func (_c *MockPasswordUsecase_Authenticate_Call) Run(run func(ctx context.Context, loginID string, password string, organizationName string)) *MockPasswordUsecase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPasswordUsecase_Authenticate_Call) Return(authTokenSet *service.AuthTokenSet, err error) *MockPasswordUsecase_Authenticate_Call {
	_c.Call.Return(authTokenSet, err)
	return _c
}

func (_c *MockPasswordUsecase_Authenticate_Call) RunAndReturn(run func(ctx context.Context, loginID string, password string, organizationName string) (*service.AuthTokenSet, error)) *MockPasswordUsecase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileQueryUsecase creates a new instance of MockProfileQueryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileQueryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileQueryUsecase {
	mock := &MockProfileQueryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileQueryUsecase is an autogenerated mock type for the ProfileQueryUsecase type
type MockProfileQueryUsecase struct {
	mock.Mock
}

type MockProfileQueryUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileQueryUsecase) EXPECT() *MockProfileQueryUsecase_Expecter {
	return &MockProfileQueryUsecase_Expecter{mock: &_m.Mock}
}

// GetMyProfile provides a mock function for the type MockProfileQueryUsecase
func (_mock *MockProfileQueryUsecase) GetMyProfile(ctx context.Context, operator domain.UserInterface) (*domain.ProfileModel, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetMyProfile")
	}

	var r0 *domain.ProfileModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.ProfileModel, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.ProfileModel); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfileModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileQueryUsecase_GetMyProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyProfile'
type MockProfileQueryUsecase_GetMyProfile_Call struct {
	*mock.Call
}

// GetMyProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockProfileQueryUsecase_Expecter) GetMyProfile(ctx interface{}, operator interface{}) *MockProfileQueryUsecase_GetMyProfile_Call {
	return &MockProfileQueryUsecase_GetMyProfile_Call{Call: _e.mock.On("GetMyProfile", ctx, operator)}
}

func (_c *MockProfileQueryUsecase_GetMyProfile_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockProfileQueryUsecase_GetMyProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileQueryUsecase_GetMyProfile_Call) Return(profileModel *domain.ProfileModel, err error) *MockProfileQueryUsecase_GetMyProfile_Call {
	_c.Call.Return(profileModel, err)
	return _c
}

func (_c *MockProfileQueryUsecase_GetMyProfile_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.ProfileModel, error)) *MockProfileQueryUsecase_GetMyProfile_Call {
	_c.Call.Return(run)
	return _c
}
