---
# Shared Jaeger configuration for both backend-gin-gorm and backend-express-drizzle
# Note: ports and networks must be overridden in each backend's compose file
services:
  local-jaeger-base:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.11.0
    container_name: local-jaeger
    healthcheck:
      test: ["CMD", "wget", "-qO-", "localhost:13133/status"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - NET_RAW
      - SETFCAP
      - SYS_CHROOT
