---
version: "3"

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

vars:
  GO_PROJECTS:
    - hello-world
    - third-party-library
    - cocotola-app
    - cocotola-auth
    - cocotola-init
    - cocotola-empty
    - cocotola-lib
  GO_APPS:
    - cocotola-empty

tasks:
  init:
    cmds:
      - go work init
      - go work use -r .

  gazelle:
    cmds:
      - bazelisk run //:gazelle -- -build_tags=small,medium,large

  mod-tidy:
    cmds:
      - bazelisk run @rules_go//go -- mod tidy

  check-go-project:
    cmds:
      - |
        cd {{ .GO_PROJECT }}
        golangci-lint run --config ../.golangci.yml --timeout=5m
    requires:
      vars: [GO_PROJECT]

  check:
    cmds:
      - for:
          var: GO_PROJECTS
        task: check-go-project
        vars:
          GO_PROJECT: "{{ .ITEM }}"

  gen-code-project:
    cmds:
      - |
        cd {{ .GO_PROJECT }}
        mockery
    requires:
      vars: [GO_PROJECT]

  gen-code:
    cmds:
      - for:
          var: GO_PROJECTS
        task: gen-code-project
        vars:
          GO_PROJECT: "{{ .ITEM }}"

  push-project:
    cmds:
      - bazelisk run //{{ .PROJECT }}:push -- --tag {{ .TAG }}
    requires:
      vars: [PROJECT, TAG]

  push:
    cmds:
      - for:
          var: GO_APPS
        task: push-project
        vars:
          PROJECT: "{{ .ITEM }}"
    requires:
      vars: [TAG]

  build-go-project:
    cmds:
      - bazelisk run //{{ .PROJECT }}:load
    requires:
      vars: [PROJECT]

  build:
    cmds:
      - for:
          var: GO_APPS
        task: build-go-project
        vars:
          PROJECT: "{{ .ITEM }}"

  test:
    cmds:
      - docker compose -f compose.test.yml up -d --wait
      - rm -f ./coverage.lcov
      - bazelisk test //... --collect_code_coverage=true --test_output=errors --test_timeout=60 --test_size_filters=small,medium --cache_test_results=no
      - bazelisk coverage //... --combined_report=lcov --test_size_filters=small,medium
      - |
        OUTPUT_PATH=$(bazelisk info output_path)
        cp "${OUTPUT_PATH}/_coverage/_coverage_report.dat" ./coverage.lcov
    env:
      APP_ENV: test
      TEST_MYSQL_HOST: localhost
      TEST_MYSQL_PORT: 3307
      TEST_MYSQL_USERNAME: username
      TEST_MYSQL_PASSWORD: password
      TEST_MYSQL_DATABASE: test

  test-remote:
    cmds:
      - docker compose -f compose.test.yml up -d --wait
      - rm -f ./coverage.lcov
      - bazelisk test --config=remote //... --collect_code_coverage=true --test_output=errors --test_timeout=60 --test_size_filters=small,medium
      - bazelisk coverage --config=remote //... --combined_report=lcov --test_size_filters=small,medium
      - |
        OUTPUT_PATH=$(bazelisk info output_path)
        cp "${OUTPUT_PATH}/_coverage/_coverage_report.dat" ./coverage.lcov
    env:
      APP_ENV: test
      TEST_MYSQL_HOST: localhost
      TEST_MYSQL_PORT: 3307
      TEST_MYSQL_USERNAME: username
      TEST_MYSQL_PASSWORD: password
      TEST_MYSQL_DATABASE: test

  clear-test:
    cmds:
      - docker compose -f compose.test.yml down

  update-mod-project:
    cmds:
      - |
        cd {{ .GO_PROJECT }}
        GOPROXY=direct go get -u ./...
        go mod tidy
    requires:
      vars: [GO_PROJECT]

  update-mod:
    cmds:
      - for:
          var: GO_PROJECTS
        task: update-mod-project
        vars:
          GO_PROJECT: "{{ .ITEM }}"

  run-hello-world:
    cmds:
      - bazelisk run //hello-world:hello-world
  run-hello-world-remote:
    cmds:
      - bazelisk run --config=remote //hello-world:hello-world

  run-third-party-library:
    cmds:
      - bazelisk run //third-party-library:third-party-library
  run-third-party-library-remote:
    cmds:
      - bazelisk run --config=remote //third-party-library:third-party-library

  run-cocotola-empty:
    cmds:
      - bazelisk run //cocotola-empty:cocotola-empty
  run-cocotola-empty-remote:
    cmds:
      - bazelisk run --config=remote //cocotola-empty:cocotola-empty

  run-cocotola-init:
    cmds:
      - docker compose -f compose.local.jaeger.yml up -d --wait
      - bazelisk run //cocotola-init:cocotola-init

  run-cocotola-auth:
    cmds:
      - docker compose -f compose.local.jaeger.yml up -d --wait
      - bazelisk run //cocotola-auth:cocotola-auth

  run-cocotola-app:
    cmds:
      - task: run-cocotola-init
      - docker compose -f compose.local.jaeger.yml up -d --wait
      - bazelisk run //cocotola-app:cocotola-app

  clear-local-infra:
    cmds:
      - docker compose -f compose.local.jaeger.yml down

  build-hello-world:
    cmds:
      - bazelisk run //hello-world:load
  build-hello-world-remote:
    cmds:
      - bazelisk run --config=remote //hello-world:load

  build-third-party-library:
    cmds:
      - bazelisk run //third-party-library:load
  build-third-party-library-remote:
    cmds:
      - bazelisk run --config=remote //third-party-library:load

  build-cocotola-empty:
    cmds:
      - bazelisk run //cocotola-empty:load
  build-cocotola-empty-remote:
    cmds:
      - bazelisk run --config=remote //cocotola-empty:load

  download-openapi-yaml:
    desc: "Download openapi.yaml from Apidog"
    cmds:
      - scripts/download-openapi-yaml.sh
      - mv openapi.yaml openapi/openapi.yaml
      - echo "✅ openapi.yaml downloaded to openapi/openapi.yaml"

  generate-openapi:
    desc: "Generate OpenAPI models using oapi-codegen"
    cmds:
      - rm -rf cocotola-auth/openapi/openapi.go || true
      - |
        oapi-codegen -package=openapi -generate=models -o=cocotola-auth/openapi/openapi.go openapi/openapi.yaml
      - go fmt cocotola-auth/openapi/openapi.go || true
      - echo "✅ Models generated"

  kics:
    cmds:
      - docker run -t -v ./:/path checkmarx/kics scan -p /path --config /path/.github/kics.yml
