---
version: "3"

vars:
  GO_PROJECTS:
    - hello-world
    - third-party-library
    - moonbeam

tasks:
  init:
    cmds:
      - go work init
      - go work use -r .

  gazelle:
    cmds:
      - bazelisk run //:gazelle -- -build_tags=small,medium,large

  mod-tidy:
    cmds:
      - bazelisk run @rules_go//go -- mod tidy

  check-go-project:
    cmds:
      - |
        cd {{ .GO_PROJECT }}
        golangci-lint run --config ../.golangci.yml --timeout=5m
    requires:
      vars: [GO_PROJECT]

  check:
    cmds:
      - for:
          var: GO_PROJECTS
        task: check-go-project
        vars:
          GO_PROJECT: "{{ .ITEM }}"

  update-mod-project:
    cmds:
      - |
        cd {{ .GO_PROJECT }}
        GOPROXY=direct go get -u ./...
        go mod tidy
    requires:
      vars: [GO_PROJECT]

  update-mod:
    cmds:
      - for:
          var: GO_PROJECTS
        task: update-mod-project
        vars:
          GO_PROJECT: "{{ .ITEM }}"

  run-hello-world:
    cmds:
      - bazelisk run //hello-world:hello-world

  run-hello-world-remote:
    cmds:
      - bazelisk run --config=remote //hello-world:hello-world

  run-third-party-library:
    cmds:
      - bazelisk run //third-party-library:third-party-library

  run-third-party-library-remote:
    cmds:
      - bazelisk run --config=remote //third-party-library:third-party-library

  build-hello-world:
    cmds:
      - bazelisk run //hello-world:load

  build-hello-world-remote:
    cmds:
      - bazelisk run --config=remote //hello-world:load

  build-third-party-library:
    cmds:
      - bazelisk run //third-party-library:load

  build-third-party-library-remote:
    cmds:
      - bazelisk run --config=remote //third-party-library:load
