/*
 * cocotola
 *
 * cocotola
 *
 * API version: 1.0.0
 * Contact: support@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GuestAuthRequest struct {

	OrganizationName string `json:"organizationName" validate:"regexp=^.*$"`
}
