/*
 * cocotola
 *
 * cocotola
 *
 * API version: 1.0.0
 * Contact: support@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetMyProfileResponse struct {

	LoginID string `json:"loginId"`

	Username string `json:"username"`

	OrganizationID int32 `json:"organizationId"`

	OrganizationName string `json:"organizationName"`

	PrivateSpaceID int32 `json:"privateSpaceId"`
}
