/*
 * cocotola
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PasswordAuthRequest struct {

	LoginID string `json:"loginId" binding:"required"`

	Password string `json:"password" binding:"required"`

	OrganizationName string `json:"organizationName" binding:"required"`
}
