/*
 * cocotola
 *
 * cocotola
 *
 * API version: 1.0.0
 * Contact: support@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PasswordAuthRequest struct {

	LoginID string `json:"loginId" validate:"regexp=^.*$"`

	Password string `json:"password" validate:"regexp=^.*$"`

	OrganizationName string `json:"organizationName" validate:"regexp=^.*$"`
}
