/*
 * cocotola
 *
 * cocotola
 *
 * API version: 1.0.0
 * Contact: support@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthResponse struct {

	AccessToken string `json:"accessToken" validate:"regexp=^.*$"`

	RefreshToken string `json:"refreshToken" validate:"regexp=^.*$"`
}
