// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

// GetMyProfileResponse defines model for GetMyProfileResponse.
type GetMyProfileResponse struct {
	LoginID          string `json:"loginId"`
	OrganizationID   int32  `json:"organizationId"`
	OrganizationName string `json:"organizationName"`
	PersonalSpaceID  *int32 `json:"personalSpaceId"`
	Username         string `json:"username"`
}

// GuestAuthRequest defines model for GuestAuthRequest.
type GuestAuthRequest struct {
	OrganizationName string `binding:"required,min=1,max=20" json:"organizationName"`
}

// PasswordAuthRequest defines model for PasswordAuthRequest.
type PasswordAuthRequest struct {
	LoginID          string `json:"loginId"`
	OrganizationName string `json:"organizationName"`
	Password         string `json:"password"`
}

// GuestAuthenticationJSONRequestBody defines body for GuestAuthentication for application/json ContentType.
type GuestAuthenticationJSONRequestBody = GuestAuthRequest

// PasswordAuthenticationJSONRequestBody defines body for PasswordAuthentication for application/json ContentType.
type PasswordAuthenticationJSONRequestBody = PasswordAuthRequest
