// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package profile_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.25/cocotola-auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetMyProfileQueryRepository creates a new instance of MockGetMyProfileQueryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetMyProfileQueryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetMyProfileQueryRepository {
	mock := &MockGetMyProfileQueryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetMyProfileQueryRepository is an autogenerated mock type for the GetMyProfileQueryRepository type
type MockGetMyProfileQueryRepository struct {
	mock.Mock
}

type MockGetMyProfileQueryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetMyProfileQueryRepository) EXPECT() *MockGetMyProfileQueryRepository_Expecter {
	return &MockGetMyProfileQueryRepository_Expecter{mock: &_m.Mock}
}

// GetOrganization provides a mock function for the type MockGetMyProfileQueryRepository
func (_mock *MockGetMyProfileQueryRepository) GetOrganization(ctx context.Context, operator domain.UserInterface) (*domain.Organization, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.Organization, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.Organization); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetMyProfileQueryRepository_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type MockGetMyProfileQueryRepository_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockGetMyProfileQueryRepository_Expecter) GetOrganization(ctx interface{}, operator interface{}) *MockGetMyProfileQueryRepository_GetOrganization_Call {
	return &MockGetMyProfileQueryRepository_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, operator)}
}

func (_c *MockGetMyProfileQueryRepository_GetOrganization_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockGetMyProfileQueryRepository_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetMyProfileQueryRepository_GetOrganization_Call) Return(organization *domain.Organization, err error) *MockGetMyProfileQueryRepository_GetOrganization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockGetMyProfileQueryRepository_GetOrganization_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.Organization, error)) *MockGetMyProfileQueryRepository_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalSpace provides a mock function for the type MockGetMyProfileQueryRepository
func (_mock *MockGetMyProfileQueryRepository) GetPersonalSpace(ctx context.Context, operator domain.UserInterface) (*domain.Space, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalSpace")
	}

	var r0 *domain.Space
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.Space, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.Space); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Space)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetMyProfileQueryRepository_GetPersonalSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalSpace'
type MockGetMyProfileQueryRepository_GetPersonalSpace_Call struct {
	*mock.Call
}

// GetPersonalSpace is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockGetMyProfileQueryRepository_Expecter) GetPersonalSpace(ctx interface{}, operator interface{}) *MockGetMyProfileQueryRepository_GetPersonalSpace_Call {
	return &MockGetMyProfileQueryRepository_GetPersonalSpace_Call{Call: _e.mock.On("GetPersonalSpace", ctx, operator)}
}

func (_c *MockGetMyProfileQueryRepository_GetPersonalSpace_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockGetMyProfileQueryRepository_GetPersonalSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetMyProfileQueryRepository_GetPersonalSpace_Call) Return(space *domain.Space, err error) *MockGetMyProfileQueryRepository_GetPersonalSpace_Call {
	_c.Call.Return(space, err)
	return _c
}

func (_c *MockGetMyProfileQueryRepository_GetPersonalSpace_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.Space, error)) *MockGetMyProfileQueryRepository_GetPersonalSpace_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockGetMyProfileQueryRepository
func (_mock *MockGetMyProfileQueryRepository) GetUser(ctx context.Context, operator domain.UserInterface) (*domain.User, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.User, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.User); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetMyProfileQueryRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockGetMyProfileQueryRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockGetMyProfileQueryRepository_Expecter) GetUser(ctx interface{}, operator interface{}) *MockGetMyProfileQueryRepository_GetUser_Call {
	return &MockGetMyProfileQueryRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, operator)}
}

func (_c *MockGetMyProfileQueryRepository_GetUser_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockGetMyProfileQueryRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetMyProfileQueryRepository_GetUser_Call) Return(user *domain.User, err error) *MockGetMyProfileQueryRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockGetMyProfileQueryRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.User, error)) *MockGetMyProfileQueryRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileUsecaseRepository creates a new instance of MockProfileUsecaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileUsecaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileUsecaseRepository {
	mock := &MockProfileUsecaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileUsecaseRepository is an autogenerated mock type for the ProfileUsecaseRepository type
type MockProfileUsecaseRepository struct {
	mock.Mock
}

type MockProfileUsecaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileUsecaseRepository) EXPECT() *MockProfileUsecaseRepository_Expecter {
	return &MockProfileUsecaseRepository_Expecter{mock: &_m.Mock}
}

// GetOrganization provides a mock function for the type MockProfileUsecaseRepository
func (_mock *MockProfileUsecaseRepository) GetOrganization(ctx context.Context, operator domain.UserInterface) (*domain.Organization, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.Organization, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.Organization); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecaseRepository_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type MockProfileUsecaseRepository_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockProfileUsecaseRepository_Expecter) GetOrganization(ctx interface{}, operator interface{}) *MockProfileUsecaseRepository_GetOrganization_Call {
	return &MockProfileUsecaseRepository_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, operator)}
}

func (_c *MockProfileUsecaseRepository_GetOrganization_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockProfileUsecaseRepository_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileUsecaseRepository_GetOrganization_Call) Return(organization *domain.Organization, err error) *MockProfileUsecaseRepository_GetOrganization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockProfileUsecaseRepository_GetOrganization_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.Organization, error)) *MockProfileUsecaseRepository_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalSpace provides a mock function for the type MockProfileUsecaseRepository
func (_mock *MockProfileUsecaseRepository) GetPersonalSpace(ctx context.Context, operator domain.UserInterface) (*domain.Space, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalSpace")
	}

	var r0 *domain.Space
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.Space, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.Space); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Space)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecaseRepository_GetPersonalSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalSpace'
type MockProfileUsecaseRepository_GetPersonalSpace_Call struct {
	*mock.Call
}

// GetPersonalSpace is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockProfileUsecaseRepository_Expecter) GetPersonalSpace(ctx interface{}, operator interface{}) *MockProfileUsecaseRepository_GetPersonalSpace_Call {
	return &MockProfileUsecaseRepository_GetPersonalSpace_Call{Call: _e.mock.On("GetPersonalSpace", ctx, operator)}
}

func (_c *MockProfileUsecaseRepository_GetPersonalSpace_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockProfileUsecaseRepository_GetPersonalSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileUsecaseRepository_GetPersonalSpace_Call) Return(space *domain.Space, err error) *MockProfileUsecaseRepository_GetPersonalSpace_Call {
	_c.Call.Return(space, err)
	return _c
}

func (_c *MockProfileUsecaseRepository_GetPersonalSpace_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.Space, error)) *MockProfileUsecaseRepository_GetPersonalSpace_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockProfileUsecaseRepository
func (_mock *MockProfileUsecaseRepository) GetUser(ctx context.Context, operator domain.UserInterface) (*domain.User, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.User, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.User); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileUsecaseRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockProfileUsecaseRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockProfileUsecaseRepository_Expecter) GetUser(ctx interface{}, operator interface{}) *MockProfileUsecaseRepository_GetUser_Call {
	return &MockProfileUsecaseRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, operator)}
}

func (_c *MockProfileUsecaseRepository_GetUser_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockProfileUsecaseRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileUsecaseRepository_GetUser_Call) Return(user *domain.User, err error) *MockProfileUsecaseRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockProfileUsecaseRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.User, error)) *MockProfileUsecaseRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
