// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/mocoarow/cocotola-1.25/cocotola-auth/service"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type MockRepositoryFactory struct {
	mock.Mock
}

type MockRepositoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryFactory) EXPECT() *MockRepositoryFactory_Expecter {
	return &MockRepositoryFactory_Expecter{mock: &_m.Mock}
}

// NewAuthorizationManager provides a mock function with given fields: ctx
func (_m *MockRepositoryFactory) NewAuthorizationManager(ctx context.Context) (service.AuthorizationManager, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewAuthorizationManager")
	}

	var r0 service.AuthorizationManager
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.AuthorizationManager, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.AuthorizationManager); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AuthorizationManager)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryFactory_NewAuthorizationManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAuthorizationManager'
type MockRepositoryFactory_NewAuthorizationManager_Call struct {
	*mock.Call
}

// NewAuthorizationManager is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryFactory_Expecter) NewAuthorizationManager(ctx interface{}) *MockRepositoryFactory_NewAuthorizationManager_Call {
	return &MockRepositoryFactory_NewAuthorizationManager_Call{Call: _e.mock.On("NewAuthorizationManager", ctx)}
}

func (_c *MockRepositoryFactory_NewAuthorizationManager_Call) Run(run func(ctx context.Context)) *MockRepositoryFactory_NewAuthorizationManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryFactory_NewAuthorizationManager_Call) Return(_a0 service.AuthorizationManager, _a1 error) *MockRepositoryFactory_NewAuthorizationManager_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryFactory_NewAuthorizationManager_Call) RunAndReturn(run func(context.Context) (service.AuthorizationManager, error)) *MockRepositoryFactory_NewAuthorizationManager_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrganizationRepository provides a mock function with given fields: ctx
func (_m *MockRepositoryFactory) NewOrganizationRepository(ctx context.Context) service.OrganizationRepository {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewOrganizationRepository")
	}

	var r0 service.OrganizationRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.OrganizationRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.OrganizationRepository)
		}
	}

	return r0
}

// MockRepositoryFactory_NewOrganizationRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewOrganizationRepository'
type MockRepositoryFactory_NewOrganizationRepository_Call struct {
	*mock.Call
}

// NewOrganizationRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryFactory_Expecter) NewOrganizationRepository(ctx interface{}) *MockRepositoryFactory_NewOrganizationRepository_Call {
	return &MockRepositoryFactory_NewOrganizationRepository_Call{Call: _e.mock.On("NewOrganizationRepository", ctx)}
}

func (_c *MockRepositoryFactory_NewOrganizationRepository_Call) Run(run func(ctx context.Context)) *MockRepositoryFactory_NewOrganizationRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryFactory_NewOrganizationRepository_Call) Return(_a0 service.OrganizationRepository) *MockRepositoryFactory_NewOrganizationRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryFactory_NewOrganizationRepository_Call) RunAndReturn(run func(context.Context) service.OrganizationRepository) *MockRepositoryFactory_NewOrganizationRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpaceManager provides a mock function with given fields: ctx
func (_m *MockRepositoryFactory) NewSpaceManager(ctx context.Context) (service.SpaceManager, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewSpaceManager")
	}

	var r0 service.SpaceManager
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.SpaceManager, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.SpaceManager); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.SpaceManager)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryFactory_NewSpaceManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSpaceManager'
type MockRepositoryFactory_NewSpaceManager_Call struct {
	*mock.Call
}

// NewSpaceManager is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryFactory_Expecter) NewSpaceManager(ctx interface{}) *MockRepositoryFactory_NewSpaceManager_Call {
	return &MockRepositoryFactory_NewSpaceManager_Call{Call: _e.mock.On("NewSpaceManager", ctx)}
}

func (_c *MockRepositoryFactory_NewSpaceManager_Call) Run(run func(ctx context.Context)) *MockRepositoryFactory_NewSpaceManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryFactory_NewSpaceManager_Call) Return(_a0 service.SpaceManager, _a1 error) *MockRepositoryFactory_NewSpaceManager_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryFactory_NewSpaceManager_Call) RunAndReturn(run func(context.Context) (service.SpaceManager, error)) *MockRepositoryFactory_NewSpaceManager_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpaceRepository provides a mock function with given fields: ctx
func (_m *MockRepositoryFactory) NewSpaceRepository(ctx context.Context) service.SpaceRepository {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewSpaceRepository")
	}

	var r0 service.SpaceRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.SpaceRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.SpaceRepository)
		}
	}

	return r0
}

// MockRepositoryFactory_NewSpaceRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSpaceRepository'
type MockRepositoryFactory_NewSpaceRepository_Call struct {
	*mock.Call
}

// NewSpaceRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryFactory_Expecter) NewSpaceRepository(ctx interface{}) *MockRepositoryFactory_NewSpaceRepository_Call {
	return &MockRepositoryFactory_NewSpaceRepository_Call{Call: _e.mock.On("NewSpaceRepository", ctx)}
}

func (_c *MockRepositoryFactory_NewSpaceRepository_Call) Run(run func(ctx context.Context)) *MockRepositoryFactory_NewSpaceRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryFactory_NewSpaceRepository_Call) Return(_a0 service.SpaceRepository) *MockRepositoryFactory_NewSpaceRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryFactory_NewSpaceRepository_Call) RunAndReturn(run func(context.Context) service.SpaceRepository) *MockRepositoryFactory_NewSpaceRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserGroupRepository provides a mock function with given fields: ctx
func (_m *MockRepositoryFactory) NewUserGroupRepository(ctx context.Context) service.UserGroupRepository {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewUserGroupRepository")
	}

	var r0 service.UserGroupRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.UserGroupRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.UserGroupRepository)
		}
	}

	return r0
}

// MockRepositoryFactory_NewUserGroupRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUserGroupRepository'
type MockRepositoryFactory_NewUserGroupRepository_Call struct {
	*mock.Call
}

// NewUserGroupRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryFactory_Expecter) NewUserGroupRepository(ctx interface{}) *MockRepositoryFactory_NewUserGroupRepository_Call {
	return &MockRepositoryFactory_NewUserGroupRepository_Call{Call: _e.mock.On("NewUserGroupRepository", ctx)}
}

func (_c *MockRepositoryFactory_NewUserGroupRepository_Call) Run(run func(ctx context.Context)) *MockRepositoryFactory_NewUserGroupRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryFactory_NewUserGroupRepository_Call) Return(_a0 service.UserGroupRepository) *MockRepositoryFactory_NewUserGroupRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryFactory_NewUserGroupRepository_Call) RunAndReturn(run func(context.Context) service.UserGroupRepository) *MockRepositoryFactory_NewUserGroupRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository provides a mock function with given fields: ctx
func (_m *MockRepositoryFactory) NewUserRepository(ctx context.Context) service.UserRepository {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewUserRepository")
	}

	var r0 service.UserRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.UserRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.UserRepository)
		}
	}

	return r0
}

// MockRepositoryFactory_NewUserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUserRepository'
type MockRepositoryFactory_NewUserRepository_Call struct {
	*mock.Call
}

// NewUserRepository is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryFactory_Expecter) NewUserRepository(ctx interface{}) *MockRepositoryFactory_NewUserRepository_Call {
	return &MockRepositoryFactory_NewUserRepository_Call{Call: _e.mock.On("NewUserRepository", ctx)}
}

func (_c *MockRepositoryFactory_NewUserRepository_Call) Run(run func(ctx context.Context)) *MockRepositoryFactory_NewUserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepositoryFactory_NewUserRepository_Call) Return(_a0 service.UserRepository) *MockRepositoryFactory_NewUserRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryFactory_NewUserRepository_Call) RunAndReturn(run func(context.Context) service.UserRepository) *MockRepositoryFactory_NewUserRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryFactory creates a new instance of MockRepositoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryFactory {
	mock := &MockRepositoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
