---
all: false
dir: '{{.InterfaceDir}}'
filename: mocks.go
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
recursive: false
packages:
  github.com/mocoarow/cocotola-1.25/cocotola-auth/service:
    config:
      dir: ./service/mocks
      filename: '{{.InterfaceName}}.go'
      outpkg: mocks
    interfaces:
      RepositoryFactory: {}
      UserRepository: {}
      TransactionManager: {}
