---
all: false
dir: '{{.InterfaceDir}}'
filename: mocks_test.go
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}_test'
recursive: false
packages:
  github.com/mocoarow/cocotola-1.25/cocotola-app:
    config:
      all: true
