CREATE TABLE casbin_rule (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ptype VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    v0 VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    v1 VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    v2 VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    v3 VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    v4 VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    v5 VARCHAR(100) COLLATE utf8mb4_bin DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
