// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mocoarow/cocotola-1.25/moonbeam/user/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/mocoarow/cocotola-1.25/moonbeam/user/service"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateSystemOwner provides a mock function with given fields: ctx, operator, organizationID
func (_m *MockUserRepository) CreateSystemOwner(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserID, error) {
	ret := _m.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSystemOwner")
	}

	var r0 *domain.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.UserID, error)); ok {
		return rf(ctx, operator, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) *domain.UserID); ok {
		r0 = rf(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) error); ok {
		r1 = rf(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CreateSystemOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystemOwner'
type MockUserRepository_CreateSystemOwner_Call struct {
	*mock.Call
}

// CreateSystemOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserRepository_Expecter) CreateSystemOwner(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserRepository_CreateSystemOwner_Call {
	return &MockUserRepository_CreateSystemOwner_Call{Call: _e.mock.On("CreateSystemOwner", ctx, operator, organizationID)}
}

func (_c *MockUserRepository_CreateSystemOwner_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID)) *MockUserRepository_CreateSystemOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SystemAdminInterface), args[2].(*domain.OrganizationID))
	})
	return _c
}

func (_c *MockUserRepository_CreateSystemOwner_Call) Return(_a0 *domain.UserID, _a1 error) *MockUserRepository_CreateSystemOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CreateSystemOwner_Call) RunAndReturn(run func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.UserID, error)) *MockUserRepository_CreateSystemOwner_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, operator, param
func (_m *MockUserRepository) CreateUser(ctx context.Context, operator domain.UserInterface, param *service.CreateUserParameter) (*domain.UserID, error) {
	ret := _m.Called(ctx, operator, param)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *service.CreateUserParameter) (*domain.UserID, error)); ok {
		return rf(ctx, operator, param)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *service.CreateUserParameter) *domain.UserID); ok {
		r0 = rf(ctx, operator, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *service.CreateUserParameter) error); ok {
		r1 = rf(ctx, operator, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - param *service.CreateUserParameter
func (_e *MockUserRepository_Expecter) CreateUser(ctx interface{}, operator interface{}, param interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, operator, param)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, operator domain.UserInterface, param *service.CreateUserParameter)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*service.CreateUserParameter))
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(_a0 *domain.UserID, _a1 error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, domain.UserInterface, *service.CreateUserParameter) (*domain.UserID, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindOwnerByLoginID provides a mock function with given fields: ctx, operator, loginID
func (_m *MockUserRepository) FindOwnerByLoginID(ctx context.Context, operator domain.SystemOwnerInterface, loginID string) (*domain.Owner, error) {
	ret := _m.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindOwnerByLoginID")
	}

	var r0 *domain.Owner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string) (*domain.Owner, error)); ok {
		return rf(ctx, operator, loginID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string) *domain.Owner); ok {
		r0 = rf(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Owner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string) error); ok {
		r1 = rf(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindOwnerByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOwnerByLoginID'
type MockUserRepository_FindOwnerByLoginID_Call struct {
	*mock.Call
}

// FindOwnerByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
func (_e *MockUserRepository_Expecter) FindOwnerByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockUserRepository_FindOwnerByLoginID_Call {
	return &MockUserRepository_FindOwnerByLoginID_Call{Call: _e.mock.On("FindOwnerByLoginID", ctx, operator, loginID)}
}

func (_c *MockUserRepository_FindOwnerByLoginID_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string)) *MockUserRepository_FindOwnerByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SystemOwnerInterface), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindOwnerByLoginID_Call) Return(_a0 *domain.Owner, _a1 error) *MockUserRepository_FindOwnerByLoginID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindOwnerByLoginID_Call) RunAndReturn(run func(context.Context, domain.SystemOwnerInterface, string) (*domain.Owner, error)) *MockUserRepository_FindOwnerByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSystemOwnerByOrganizationID provides a mock function with given fields: ctx, operator, organizationID
func (_m *MockUserRepository) FindSystemOwnerByOrganizationID(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.SystemOwner, error) {
	ret := _m.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationID")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.SystemOwner, error)); ok {
		return rf(ctx, operator, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) *domain.SystemOwner); ok {
		r0 = rf(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) error); ok {
		r1 = rf(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindSystemOwnerByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationID'
type MockUserRepository_FindSystemOwnerByOrganizationID_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserRepository_Expecter) FindSystemOwnerByOrganizationID(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserRepository_FindSystemOwnerByOrganizationID_Call {
	return &MockUserRepository_FindSystemOwnerByOrganizationID_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationID", ctx, operator, organizationID)}
}

func (_c *MockUserRepository_FindSystemOwnerByOrganizationID_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID)) *MockUserRepository_FindSystemOwnerByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SystemAdminInterface), args[2].(*domain.OrganizationID))
	})
	return _c
}

func (_c *MockUserRepository_FindSystemOwnerByOrganizationID_Call) Return(_a0 *domain.SystemOwner, _a1 error) *MockUserRepository_FindSystemOwnerByOrganizationID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindSystemOwnerByOrganizationID_Call) RunAndReturn(run func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.SystemOwner, error)) *MockUserRepository_FindSystemOwnerByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// FindSystemOwnerByOrganizationName provides a mock function with given fields: ctx, operator, organizationName
func (_m *MockUserRepository) FindSystemOwnerByOrganizationName(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error) {
	ret := _m.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationName")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)); ok {
		return rf(ctx, operator, organizationName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.SystemOwner); ok {
		r0 = rf(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = rf(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindSystemOwnerByOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationName'
type MockUserRepository_FindSystemOwnerByOrganizationName_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockUserRepository_Expecter) FindSystemOwnerByOrganizationName(ctx interface{}, operator interface{}, organizationName interface{}) *MockUserRepository_FindSystemOwnerByOrganizationName_Call {
	return &MockUserRepository_FindSystemOwnerByOrganizationName_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationName", ctx, operator, organizationName)}
}

func (_c *MockUserRepository_FindSystemOwnerByOrganizationName_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockUserRepository_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SystemAdminInterface), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindSystemOwnerByOrganizationName_Call) Return(_a0 *domain.SystemOwner, _a1 error) *MockUserRepository_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindSystemOwnerByOrganizationName_Call) RunAndReturn(run func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)) *MockUserRepository_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: ctx, operator, id
func (_m *MockUserRepository) FindUserByID(ctx context.Context, operator domain.UserInterface, id *domain.UserID) (*domain.User, error) {
	ret := _m.Called(ctx, operator, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserID) (*domain.User, error)); ok {
		return rf(ctx, operator, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserID) *domain.User); ok {
		r0 = rf(ctx, operator, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *domain.UserID) error); ok {
		r1 = rf(ctx, operator, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockUserRepository_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - id *domain.UserID
func (_e *MockUserRepository_Expecter) FindUserByID(ctx interface{}, operator interface{}, id interface{}) *MockUserRepository_FindUserByID_Call {
	return &MockUserRepository_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, operator, id)}
}

func (_c *MockUserRepository_FindUserByID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, id *domain.UserID)) *MockUserRepository_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(*domain.UserID))
	})
	return _c
}

func (_c *MockUserRepository_FindUserByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindUserByID_Call) RunAndReturn(run func(context.Context, domain.UserInterface, *domain.UserID) (*domain.User, error)) *MockUserRepository_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByLoginID provides a mock function with given fields: ctx, operator, loginID
func (_m *MockUserRepository) FindUserByLoginID(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error) {
	ret := _m.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLoginID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.User, error)); ok {
		return rf(ctx, operator, loginID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.User); ok {
		r0 = rf(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = rf(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindUserByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByLoginID'
type MockUserRepository_FindUserByLoginID_Call struct {
	*mock.Call
}

// FindUserByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - loginID string
func (_e *MockUserRepository_Expecter) FindUserByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockUserRepository_FindUserByLoginID_Call {
	return &MockUserRepository_FindUserByLoginID_Call{Call: _e.mock.On("FindUserByLoginID", ctx, operator, loginID)}
}

func (_c *MockUserRepository_FindUserByLoginID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, loginID string)) *MockUserRepository_FindUserByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserInterface), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindUserByLoginID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_FindUserByLoginID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindUserByLoginID_Call) RunAndReturn(run func(context.Context, domain.UserInterface, string) (*domain.User, error)) *MockUserRepository_FindUserByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: ctx, operator, loginID, password
func (_m *MockUserRepository) VerifyPassword(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error) {
	ret := _m.Called(ctx, operator, loginID, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)); ok {
		return rf(ctx, operator, loginID, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) bool); ok {
		r0 = rf(ctx, operator, loginID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string, string) error); ok {
		r1 = rf(ctx, operator, loginID, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockUserRepository_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
//   - password string
func (_e *MockUserRepository_Expecter) VerifyPassword(ctx interface{}, operator interface{}, loginID interface{}, password interface{}) *MockUserRepository_VerifyPassword_Call {
	return &MockUserRepository_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, operator, loginID, password)}
}

func (_c *MockUserRepository_VerifyPassword_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string)) *MockUserRepository_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SystemOwnerInterface), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserRepository_VerifyPassword_Call) Return(_a0 bool, _a1 error) *MockUserRepository_VerifyPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_VerifyPassword_Call) RunAndReturn(run func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)) *MockUserRepository_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
