// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.25/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.25/cocotola-auth/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecaseGateway creates a new instance of MockUsecaseGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecaseGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecaseGateway {
	mock := &MockUsecaseGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecaseGateway is an autogenerated mock type for the UsecaseGateway type
type MockUsecaseGateway struct {
	mock.Mock
}

type MockUsecaseGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecaseGateway) EXPECT() *MockUsecaseGateway_Expecter {
	return &MockUsecaseGateway_Expecter{mock: &_m.Mock}
}

// FindSystemOwnerByOrganizationName provides a mock function for the type MockUsecaseGateway
func (_mock *MockUsecaseGateway) FindSystemOwnerByOrganizationName(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error) {
	ret := _mock.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationName")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)); ok {
		return returnFunc(ctx, operator, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.SystemOwner); ok {
		r0 = returnFunc(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationName'
type MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockUsecaseGateway_Expecter) FindSystemOwnerByOrganizationName(ctx interface{}, operator interface{}, organizationName interface{}) *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	return &MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationName", ctx, operator, organizationName)}
}

func (_c *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call) Return(systemOwner *domain.SystemOwner, err error) *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(systemOwner, err)
	return _c
}

func (_c *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error)) *MockUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByLoginID provides a mock function for the type MockUsecaseGateway
func (_mock *MockUsecaseGateway) FindUserByLoginID(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error) {
	ret := _mock.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLoginID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.User, error)); ok {
		return returnFunc(ctx, operator, loginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.User); ok {
		r0 = returnFunc(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecaseGateway_FindUserByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByLoginID'
type MockUsecaseGateway_FindUserByLoginID_Call struct {
	*mock.Call
}

// FindUserByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - loginID string
func (_e *MockUsecaseGateway_Expecter) FindUserByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockUsecaseGateway_FindUserByLoginID_Call {
	return &MockUsecaseGateway_FindUserByLoginID_Call{Call: _e.mock.On("FindUserByLoginID", ctx, operator, loginID)}
}

func (_c *MockUsecaseGateway_FindUserByLoginID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, loginID string)) *MockUsecaseGateway_FindUserByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecaseGateway_FindUserByLoginID_Call) Return(user *domain.User, err error) *MockUsecaseGateway_FindUserByLoginID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsecaseGateway_FindUserByLoginID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error)) *MockUsecaseGateway_FindUserByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockUsecaseGateway
func (_mock *MockUsecaseGateway) GetUserInfo(ctx context.Context, tokenString string) (*service.UserInfo, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *service.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.UserInfo, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.UserInfo); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecaseGateway_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockUsecaseGateway_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockUsecaseGateway_Expecter) GetUserInfo(ctx interface{}, tokenString interface{}) *MockUsecaseGateway_GetUserInfo_Call {
	return &MockUsecaseGateway_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, tokenString)}
}

func (_c *MockUsecaseGateway_GetUserInfo_Call) Run(run func(ctx context.Context, tokenString string)) *MockUsecaseGateway_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecaseGateway_GetUserInfo_Call) Return(userInfo *service.UserInfo, err error) *MockUsecaseGateway_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockUsecaseGateway_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*service.UserInfo, error)) *MockUsecaseGateway_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type MockUsecaseGateway
func (_mock *MockUsecaseGateway) VerifyPassword(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error) {
	ret := _mock.Called(ctx, operator, loginID, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)); ok {
		return returnFunc(ctx, operator, loginID, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) bool); ok {
		r0 = returnFunc(ctx, operator, loginID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecaseGateway_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockUsecaseGateway_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
//   - password string
func (_e *MockUsecaseGateway_Expecter) VerifyPassword(ctx interface{}, operator interface{}, loginID interface{}, password interface{}) *MockUsecaseGateway_VerifyPassword_Call {
	return &MockUsecaseGateway_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, operator, loginID, password)}
}

func (_c *MockUsecaseGateway_VerifyPassword_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string)) *MockUsecaseGateway_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsecaseGateway_VerifyPassword_Call) Return(b bool, err error) *MockUsecaseGateway_VerifyPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUsecaseGateway_VerifyPassword_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error)) *MockUsecaseGateway_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifyAccessTokenQueryGateway creates a new instance of MockVerifyAccessTokenQueryGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyAccessTokenQueryGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyAccessTokenQueryGateway {
	mock := &MockVerifyAccessTokenQueryGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifyAccessTokenQueryGateway is an autogenerated mock type for the VerifyAccessTokenQueryGateway type
type MockVerifyAccessTokenQueryGateway struct {
	mock.Mock
}

type MockVerifyAccessTokenQueryGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifyAccessTokenQueryGateway) EXPECT() *MockVerifyAccessTokenQueryGateway_Expecter {
	return &MockVerifyAccessTokenQueryGateway_Expecter{mock: &_m.Mock}
}

// FindSystemOwnerByOrganizationName provides a mock function for the type MockVerifyAccessTokenQueryGateway
func (_mock *MockVerifyAccessTokenQueryGateway) FindSystemOwnerByOrganizationName(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error) {
	ret := _mock.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationName")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)); ok {
		return returnFunc(ctx, operator, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.SystemOwner); ok {
		r0 = returnFunc(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationName'
type MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockVerifyAccessTokenQueryGateway_Expecter) FindSystemOwnerByOrganizationName(ctx interface{}, operator interface{}, organizationName interface{}) *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	return &MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationName", ctx, operator, organizationName)}
}

func (_c *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call) Return(systemOwner *domain.SystemOwner, err error) *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(systemOwner, err)
	return _c
}

func (_c *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error)) *MockVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByLoginID provides a mock function for the type MockVerifyAccessTokenQueryGateway
func (_mock *MockVerifyAccessTokenQueryGateway) FindUserByLoginID(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error) {
	ret := _mock.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLoginID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.User, error)); ok {
		return returnFunc(ctx, operator, loginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.User); ok {
		r0 = returnFunc(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByLoginID'
type MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call struct {
	*mock.Call
}

// FindUserByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - loginID string
func (_e *MockVerifyAccessTokenQueryGateway_Expecter) FindUserByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	return &MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call{Call: _e.mock.On("FindUserByLoginID", ctx, operator, loginID)}
}

func (_c *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, loginID string)) *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call) Return(user *domain.User, err error) *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error)) *MockVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockVerifyAccessTokenQueryGateway
func (_mock *MockVerifyAccessTokenQueryGateway) GetUserInfo(ctx context.Context, tokenString string) (*service.UserInfo, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *service.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.UserInfo, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.UserInfo); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifyAccessTokenQueryGateway_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockVerifyAccessTokenQueryGateway_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockVerifyAccessTokenQueryGateway_Expecter) GetUserInfo(ctx interface{}, tokenString interface{}) *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	return &MockVerifyAccessTokenQueryGateway_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, tokenString)}
}

func (_c *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call) Run(run func(ctx context.Context, tokenString string)) *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call) Return(userInfo *service.UserInfo, err error) *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*service.UserInfo, error)) *MockVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifyPasswordCommandGateway creates a new instance of MockVerifyPasswordCommandGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyPasswordCommandGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyPasswordCommandGateway {
	mock := &MockVerifyPasswordCommandGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifyPasswordCommandGateway is an autogenerated mock type for the VerifyPasswordCommandGateway type
type MockVerifyPasswordCommandGateway struct {
	mock.Mock
}

type MockVerifyPasswordCommandGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifyPasswordCommandGateway) EXPECT() *MockVerifyPasswordCommandGateway_Expecter {
	return &MockVerifyPasswordCommandGateway_Expecter{mock: &_m.Mock}
}

// VerifyPassword provides a mock function for the type MockVerifyPasswordCommandGateway
func (_mock *MockVerifyPasswordCommandGateway) VerifyPassword(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error) {
	ret := _mock.Called(ctx, operator, loginID, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)); ok {
		return returnFunc(ctx, operator, loginID, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) bool); ok {
		r0 = returnFunc(ctx, operator, loginID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifyPasswordCommandGateway_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockVerifyPasswordCommandGateway_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
//   - password string
func (_e *MockVerifyPasswordCommandGateway_Expecter) VerifyPassword(ctx interface{}, operator interface{}, loginID interface{}, password interface{}) *MockVerifyPasswordCommandGateway_VerifyPassword_Call {
	return &MockVerifyPasswordCommandGateway_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, operator, loginID, password)}
}

func (_c *MockVerifyPasswordCommandGateway_VerifyPassword_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string)) *MockVerifyPasswordCommandGateway_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVerifyPasswordCommandGateway_VerifyPassword_Call) Return(b bool, err error) *MockVerifyPasswordCommandGateway_VerifyPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockVerifyPasswordCommandGateway_VerifyPassword_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error)) *MockVerifyPasswordCommandGateway_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}
