// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.25/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.25/cocotola-auth/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUsecaseGateway creates a new instance of MockAuthUsecaseGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecaseGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecaseGateway {
	mock := &MockAuthUsecaseGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUsecaseGateway is an autogenerated mock type for the AuthUsecaseGateway type
type MockAuthUsecaseGateway struct {
	mock.Mock
}

type MockAuthUsecaseGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecaseGateway) EXPECT() *MockAuthUsecaseGateway_Expecter {
	return &MockAuthUsecaseGateway_Expecter{mock: &_m.Mock}
}

// FindSystemOwnerByOrganizationName provides a mock function for the type MockAuthUsecaseGateway
func (_mock *MockAuthUsecaseGateway) FindSystemOwnerByOrganizationName(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error) {
	ret := _mock.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationName")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)); ok {
		return returnFunc(ctx, operator, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.SystemOwner); ok {
		r0 = returnFunc(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationName'
type MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockAuthUsecaseGateway_Expecter) FindSystemOwnerByOrganizationName(ctx interface{}, operator interface{}, organizationName interface{}) *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	return &MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationName", ctx, operator, organizationName)}
}

func (_c *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call) Return(systemOwner *domain.SystemOwner, err error) *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(systemOwner, err)
	return _c
}

func (_c *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error)) *MockAuthUsecaseGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByLoginID provides a mock function for the type MockAuthUsecaseGateway
func (_mock *MockAuthUsecaseGateway) FindUserByLoginID(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error) {
	ret := _mock.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLoginID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.User, error)); ok {
		return returnFunc(ctx, operator, loginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.User); ok {
		r0 = returnFunc(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecaseGateway_FindUserByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByLoginID'
type MockAuthUsecaseGateway_FindUserByLoginID_Call struct {
	*mock.Call
}

// FindUserByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - loginID string
func (_e *MockAuthUsecaseGateway_Expecter) FindUserByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockAuthUsecaseGateway_FindUserByLoginID_Call {
	return &MockAuthUsecaseGateway_FindUserByLoginID_Call{Call: _e.mock.On("FindUserByLoginID", ctx, operator, loginID)}
}

func (_c *MockAuthUsecaseGateway_FindUserByLoginID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, loginID string)) *MockAuthUsecaseGateway_FindUserByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthUsecaseGateway_FindUserByLoginID_Call) Return(user *domain.User, err error) *MockAuthUsecaseGateway_FindUserByLoginID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthUsecaseGateway_FindUserByLoginID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error)) *MockAuthUsecaseGateway_FindUserByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockAuthUsecaseGateway
func (_mock *MockAuthUsecaseGateway) GetUserInfo(ctx context.Context, tokenString string) (*service.UserInfo, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *service.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.UserInfo, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.UserInfo); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecaseGateway_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockAuthUsecaseGateway_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthUsecaseGateway_Expecter) GetUserInfo(ctx interface{}, tokenString interface{}) *MockAuthUsecaseGateway_GetUserInfo_Call {
	return &MockAuthUsecaseGateway_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, tokenString)}
}

func (_c *MockAuthUsecaseGateway_GetUserInfo_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthUsecaseGateway_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthUsecaseGateway_GetUserInfo_Call) Return(userInfo *service.UserInfo, err error) *MockAuthUsecaseGateway_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockAuthUsecaseGateway_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*service.UserInfo, error)) *MockAuthUsecaseGateway_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type MockAuthUsecaseGateway
func (_mock *MockAuthUsecaseGateway) VerifyPassword(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error) {
	ret := _mock.Called(ctx, operator, loginID, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)); ok {
		return returnFunc(ctx, operator, loginID, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) bool); ok {
		r0 = returnFunc(ctx, operator, loginID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecaseGateway_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockAuthUsecaseGateway_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
//   - password string
func (_e *MockAuthUsecaseGateway_Expecter) VerifyPassword(ctx interface{}, operator interface{}, loginID interface{}, password interface{}) *MockAuthUsecaseGateway_VerifyPassword_Call {
	return &MockAuthUsecaseGateway_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, operator, loginID, password)}
}

func (_c *MockAuthUsecaseGateway_VerifyPassword_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string)) *MockAuthUsecaseGateway_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthUsecaseGateway_VerifyPassword_Call) Return(b bool, err error) *MockAuthUsecaseGateway_VerifyPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthUsecaseGateway_VerifyPassword_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error)) *MockAuthUsecaseGateway_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthVerifyAccessTokenQueryGateway creates a new instance of MockAuthVerifyAccessTokenQueryGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthVerifyAccessTokenQueryGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthVerifyAccessTokenQueryGateway {
	mock := &MockAuthVerifyAccessTokenQueryGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthVerifyAccessTokenQueryGateway is an autogenerated mock type for the AuthVerifyAccessTokenQueryGateway type
type MockAuthVerifyAccessTokenQueryGateway struct {
	mock.Mock
}

type MockAuthVerifyAccessTokenQueryGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthVerifyAccessTokenQueryGateway) EXPECT() *MockAuthVerifyAccessTokenQueryGateway_Expecter {
	return &MockAuthVerifyAccessTokenQueryGateway_Expecter{mock: &_m.Mock}
}

// FindSystemOwnerByOrganizationName provides a mock function for the type MockAuthVerifyAccessTokenQueryGateway
func (_mock *MockAuthVerifyAccessTokenQueryGateway) FindSystemOwnerByOrganizationName(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error) {
	ret := _mock.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationName")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)); ok {
		return returnFunc(ctx, operator, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.SystemOwner); ok {
		r0 = returnFunc(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationName'
type MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockAuthVerifyAccessTokenQueryGateway_Expecter) FindSystemOwnerByOrganizationName(ctx interface{}, operator interface{}, organizationName interface{}) *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	return &MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationName", ctx, operator, organizationName)}
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call) Return(systemOwner *domain.SystemOwner, err error) *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(systemOwner, err)
	return _c
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error)) *MockAuthVerifyAccessTokenQueryGateway_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByLoginID provides a mock function for the type MockAuthVerifyAccessTokenQueryGateway
func (_mock *MockAuthVerifyAccessTokenQueryGateway) FindUserByLoginID(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error) {
	ret := _mock.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLoginID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.User, error)); ok {
		return returnFunc(ctx, operator, loginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.User); ok {
		r0 = returnFunc(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByLoginID'
type MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call struct {
	*mock.Call
}

// FindUserByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - loginID string
func (_e *MockAuthVerifyAccessTokenQueryGateway_Expecter) FindUserByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	return &MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call{Call: _e.mock.On("FindUserByLoginID", ctx, operator, loginID)}
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, loginID string)) *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call) Return(user *domain.User, err error) *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error)) *MockAuthVerifyAccessTokenQueryGateway_FindUserByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockAuthVerifyAccessTokenQueryGateway
func (_mock *MockAuthVerifyAccessTokenQueryGateway) GetUserInfo(ctx context.Context, tokenString string) (*service.UserInfo, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *service.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.UserInfo, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.UserInfo); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthVerifyAccessTokenQueryGateway_Expecter) GetUserInfo(ctx interface{}, tokenString interface{}) *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	return &MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, tokenString)}
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call) Return(userInfo *service.UserInfo, err error) *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*service.UserInfo, error)) *MockAuthVerifyAccessTokenQueryGateway_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthVerifyPasswordCommandGateway creates a new instance of MockAuthVerifyPasswordCommandGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthVerifyPasswordCommandGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthVerifyPasswordCommandGateway {
	mock := &MockAuthVerifyPasswordCommandGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthVerifyPasswordCommandGateway is an autogenerated mock type for the AuthVerifyPasswordCommandGateway type
type MockAuthVerifyPasswordCommandGateway struct {
	mock.Mock
}

type MockAuthVerifyPasswordCommandGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthVerifyPasswordCommandGateway) EXPECT() *MockAuthVerifyPasswordCommandGateway_Expecter {
	return &MockAuthVerifyPasswordCommandGateway_Expecter{mock: &_m.Mock}
}

// VerifyPassword provides a mock function for the type MockAuthVerifyPasswordCommandGateway
func (_mock *MockAuthVerifyPasswordCommandGateway) VerifyPassword(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error) {
	ret := _mock.Called(ctx, operator, loginID, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)); ok {
		return returnFunc(ctx, operator, loginID, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) bool); ok {
		r0 = returnFunc(ctx, operator, loginID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
//   - password string
func (_e *MockAuthVerifyPasswordCommandGateway_Expecter) VerifyPassword(ctx interface{}, operator interface{}, loginID interface{}, password interface{}) *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call {
	return &MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, operator, loginID, password)}
}

func (_c *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string)) *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call) Return(b bool, err error) *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error)) *MockAuthVerifyPasswordCommandGateway_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}
