// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_test

import (
	"context"

	"github.com/mocoarow/cocotola-1.25/cocotola-auth/domain"
	"github.com/mocoarow/cocotola-1.25/cocotola-auth/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthTokenManagerCreateTokenSet creates a new instance of MockAuthTokenManagerCreateTokenSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenManagerCreateTokenSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenManagerCreateTokenSet {
	mock := &MockAuthTokenManagerCreateTokenSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthTokenManagerCreateTokenSet is an autogenerated mock type for the AuthTokenManagerCreateTokenSet type
type MockAuthTokenManagerCreateTokenSet struct {
	mock.Mock
}

type MockAuthTokenManagerCreateTokenSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenManagerCreateTokenSet) EXPECT() *MockAuthTokenManagerCreateTokenSet_Expecter {
	return &MockAuthTokenManagerCreateTokenSet_Expecter{mock: &_m.Mock}
}

// CreateTokenSet provides a mock function for the type MockAuthTokenManagerCreateTokenSet
func (_mock *MockAuthTokenManagerCreateTokenSet) CreateTokenSet(ctx context.Context, user domain.UserInterface, organizationID *domain.OrganizationID, organizationName string) (*service.AuthTokenSet, error) {
	ret := _mock.Called(ctx, user, organizationID, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenSet")
	}

	var r0 *service.AuthTokenSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.OrganizationID, string) (*service.AuthTokenSet, error)); ok {
		return returnFunc(ctx, user, organizationID, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.OrganizationID, string) *service.AuthTokenSet); ok {
		r0 = returnFunc(ctx, user, organizationID, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AuthTokenSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *domain.OrganizationID, string) error); ok {
		r1 = returnFunc(ctx, user, organizationID, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenSet'
type MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call struct {
	*mock.Call
}

// CreateTokenSet is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.UserInterface
//   - organizationID *domain.OrganizationID
//   - organizationName string
func (_e *MockAuthTokenManagerCreateTokenSet_Expecter) CreateTokenSet(ctx interface{}, user interface{}, organizationID interface{}, organizationName interface{}) *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call {
	return &MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call{Call: _e.mock.On("CreateTokenSet", ctx, user, organizationID, organizationName)}
}

func (_c *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call) Run(run func(ctx context.Context, user domain.UserInterface, organizationID *domain.OrganizationID, organizationName string)) *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call) Return(authTokenSet *service.AuthTokenSet, err error) *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call {
	_c.Call.Return(authTokenSet, err)
	return _c
}

func (_c *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call) RunAndReturn(run func(ctx context.Context, user domain.UserInterface, organizationID *domain.OrganizationID, organizationName string) (*service.AuthTokenSet, error)) *MockAuthTokenManagerCreateTokenSet_CreateTokenSet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthTokenManagerGetUserInfo creates a new instance of MockAuthTokenManagerGetUserInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenManagerGetUserInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenManagerGetUserInfo {
	mock := &MockAuthTokenManagerGetUserInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthTokenManagerGetUserInfo is an autogenerated mock type for the AuthTokenManagerGetUserInfo type
type MockAuthTokenManagerGetUserInfo struct {
	mock.Mock
}

type MockAuthTokenManagerGetUserInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenManagerGetUserInfo) EXPECT() *MockAuthTokenManagerGetUserInfo_Expecter {
	return &MockAuthTokenManagerGetUserInfo_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type MockAuthTokenManagerGetUserInfo
func (_mock *MockAuthTokenManagerGetUserInfo) GetUserInfo(ctx context.Context, tokenString string) (*service.UserInfo, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *service.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.UserInfo, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.UserInfo); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenManagerGetUserInfo_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockAuthTokenManagerGetUserInfo_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthTokenManagerGetUserInfo_Expecter) GetUserInfo(ctx interface{}, tokenString interface{}) *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call {
	return &MockAuthTokenManagerGetUserInfo_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, tokenString)}
}

func (_c *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call) Return(userInfo *service.UserInfo, err error) *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*service.UserInfo, error)) *MockAuthTokenManagerGetUserInfo_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationRepositoryGetOrganization creates a new instance of MockOrganizationRepositoryGetOrganization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepositoryGetOrganization(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepositoryGetOrganization {
	mock := &MockOrganizationRepositoryGetOrganization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizationRepositoryGetOrganization is an autogenerated mock type for the OrganizationRepositoryGetOrganization type
type MockOrganizationRepositoryGetOrganization struct {
	mock.Mock
}

type MockOrganizationRepositoryGetOrganization_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepositoryGetOrganization) EXPECT() *MockOrganizationRepositoryGetOrganization_Expecter {
	return &MockOrganizationRepositoryGetOrganization_Expecter{mock: &_m.Mock}
}

// GetOrganization provides a mock function for the type MockOrganizationRepositoryGetOrganization
func (_mock *MockOrganizationRepositoryGetOrganization) GetOrganization(ctx context.Context, operator domain.UserInterface) (*domain.Organization, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.Organization, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.Organization); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepositoryGetOrganization_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type MockOrganizationRepositoryGetOrganization_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockOrganizationRepositoryGetOrganization_Expecter) GetOrganization(ctx interface{}, operator interface{}) *MockOrganizationRepositoryGetOrganization_GetOrganization_Call {
	return &MockOrganizationRepositoryGetOrganization_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, operator)}
}

func (_c *MockOrganizationRepositoryGetOrganization_GetOrganization_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockOrganizationRepositoryGetOrganization_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepositoryGetOrganization_GetOrganization_Call) Return(organization *domain.Organization, err error) *MockOrganizationRepositoryGetOrganization_GetOrganization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepositoryGetOrganization_GetOrganization_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.Organization, error)) *MockOrganizationRepositoryGetOrganization_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationRepositoryCreateOrganization creates a new instance of MockOrganizationRepositoryCreateOrganization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepositoryCreateOrganization(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepositoryCreateOrganization {
	mock := &MockOrganizationRepositoryCreateOrganization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizationRepositoryCreateOrganization is an autogenerated mock type for the OrganizationRepositoryCreateOrganization type
type MockOrganizationRepositoryCreateOrganization struct {
	mock.Mock
}

type MockOrganizationRepositoryCreateOrganization_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepositoryCreateOrganization) EXPECT() *MockOrganizationRepositoryCreateOrganization_Expecter {
	return &MockOrganizationRepositoryCreateOrganization_Expecter{mock: &_m.Mock}
}

// CreateOrganization provides a mock function for the type MockOrganizationRepositoryCreateOrganization
func (_mock *MockOrganizationRepositoryCreateOrganization) CreateOrganization(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.OrganizationID, error) {
	ret := _mock.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 *domain.OrganizationID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.OrganizationID, error)); ok {
		return returnFunc(ctx, operator, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.OrganizationID); ok {
		r0 = returnFunc(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OrganizationID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockOrganizationRepositoryCreateOrganization_Expecter) CreateOrganization(ctx interface{}, operator interface{}, organizationName interface{}) *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call {
	return &MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, operator, organizationName)}
}

func (_c *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call) Return(organizationID *domain.OrganizationID, err error) *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call {
	_c.Call.Return(organizationID, err)
	return _c
}

func (_c *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.OrganizationID, error)) *MockOrganizationRepositoryCreateOrganization_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPairOfUserAndGroupRepository creates a new instance of MockPairOfUserAndGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPairOfUserAndGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPairOfUserAndGroupRepository {
	mock := &MockPairOfUserAndGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPairOfUserAndGroupRepository is an autogenerated mock type for the PairOfUserAndGroupRepository type
type MockPairOfUserAndGroupRepository struct {
	mock.Mock
}

type MockPairOfUserAndGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPairOfUserAndGroupRepository) EXPECT() *MockPairOfUserAndGroupRepository_Expecter {
	return &MockPairOfUserAndGroupRepository_Expecter{mock: &_m.Mock}
}

// CreatePairOfUserAndGroup provides a mock function for the type MockPairOfUserAndGroupRepository
func (_mock *MockPairOfUserAndGroupRepository) CreatePairOfUserAndGroup(ctx context.Context, operator domain.UserInterface, userID *domain.UserID, userGroupID *domain.UserGroupID) error {
	ret := _mock.Called(ctx, operator, userID, userGroupID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePairOfUserAndGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserID, *domain.UserGroupID) error); ok {
		r0 = returnFunc(ctx, operator, userID, userGroupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePairOfUserAndGroup'
type MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call struct {
	*mock.Call
}

// CreatePairOfUserAndGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - userID *domain.UserID
//   - userGroupID *domain.UserGroupID
func (_e *MockPairOfUserAndGroupRepository_Expecter) CreatePairOfUserAndGroup(ctx interface{}, operator interface{}, userID interface{}, userGroupID interface{}) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call {
	return &MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call{Call: _e.mock.On("CreatePairOfUserAndGroup", ctx, operator, userID, userGroupID)}
}

func (_c *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call) Run(run func(ctx context.Context, operator domain.UserInterface, userID *domain.UserID, userGroupID *domain.UserGroupID)) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 *domain.UserID
		if args[2] != nil {
			arg2 = args[2].(*domain.UserID)
		}
		var arg3 *domain.UserGroupID
		if args[3] != nil {
			arg3 = args[3].(*domain.UserGroupID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call) Return(err error) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, userID *domain.UserID, userGroupID *domain.UserGroupID) error) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePairOfUserAndGroupBySystemAdmin provides a mock function for the type MockPairOfUserAndGroupRepository
func (_mock *MockPairOfUserAndGroupRepository) CreatePairOfUserAndGroupBySystemAdmin(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID, userID *domain.UserID, userGroupID *domain.UserGroupID) error {
	ret := _mock.Called(ctx, operator, organizationID, userID, userGroupID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePairOfUserAndGroupBySystemAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID, *domain.UserID, *domain.UserGroupID) error); ok {
		r0 = returnFunc(ctx, operator, organizationID, userID, userGroupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePairOfUserAndGroupBySystemAdmin'
type MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call struct {
	*mock.Call
}

// CreatePairOfUserAndGroupBySystemAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationID *domain.OrganizationID
//   - userID *domain.UserID
//   - userGroupID *domain.UserGroupID
func (_e *MockPairOfUserAndGroupRepository_Expecter) CreatePairOfUserAndGroupBySystemAdmin(ctx interface{}, operator interface{}, organizationID interface{}, userID interface{}, userGroupID interface{}) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call {
	return &MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call{Call: _e.mock.On("CreatePairOfUserAndGroupBySystemAdmin", ctx, operator, organizationID, userID, userGroupID)}
}

func (_c *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID, userID *domain.UserID, userGroupID *domain.UserGroupID)) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		var arg3 *domain.UserID
		if args[3] != nil {
			arg3 = args[3].(*domain.UserID)
		}
		var arg4 *domain.UserGroupID
		if args[4] != nil {
			arg4 = args[4].(*domain.UserGroupID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call) Return(err error) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID, userID *domain.UserID, userGroupID *domain.UserGroupID) error) *MockPairOfUserAndGroupRepository_CreatePairOfUserAndGroupBySystemAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePairOfUserAndGroup provides a mock function for the type MockPairOfUserAndGroupRepository
func (_mock *MockPairOfUserAndGroupRepository) DeletePairOfUserAndGroup(ctx context.Context, operator domain.UserInterface, userID *domain.UserID, userGroupID *domain.UserGroupID) error {
	ret := _mock.Called(ctx, operator, userID, userGroupID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePairOfUserAndGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserID, *domain.UserGroupID) error); ok {
		r0 = returnFunc(ctx, operator, userID, userGroupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePairOfUserAndGroup'
type MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call struct {
	*mock.Call
}

// DeletePairOfUserAndGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - userID *domain.UserID
//   - userGroupID *domain.UserGroupID
func (_e *MockPairOfUserAndGroupRepository_Expecter) DeletePairOfUserAndGroup(ctx interface{}, operator interface{}, userID interface{}, userGroupID interface{}) *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call {
	return &MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call{Call: _e.mock.On("DeletePairOfUserAndGroup", ctx, operator, userID, userGroupID)}
}

func (_c *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call) Run(run func(ctx context.Context, operator domain.UserInterface, userID *domain.UserID, userGroupID *domain.UserGroupID)) *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 *domain.UserID
		if args[2] != nil {
			arg2 = args[2].(*domain.UserID)
		}
		var arg3 *domain.UserGroupID
		if args[3] != nil {
			arg3 = args[3].(*domain.UserGroupID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call) Return(err error) *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, userID *domain.UserID, userGroupID *domain.UserGroupID) error) *MockPairOfUserAndGroupRepository_DeletePairOfUserAndGroup_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserGroupsByUserID provides a mock function for the type MockPairOfUserAndGroupRepository
func (_mock *MockPairOfUserAndGroupRepository) FindUserGroupsByUserID(ctx context.Context, operator domain.UserInterface, userID *domain.UserID) ([]*domain.UserGroup, error) {
	ret := _mock.Called(ctx, operator, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserGroupsByUserID")
	}

	var r0 []*domain.UserGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserID) ([]*domain.UserGroup, error)); ok {
		return returnFunc(ctx, operator, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserID) []*domain.UserGroup); ok {
		r0 = returnFunc(ctx, operator, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *domain.UserID) error); ok {
		r1 = returnFunc(ctx, operator, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserGroupsByUserID'
type MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call struct {
	*mock.Call
}

// FindUserGroupsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - userID *domain.UserID
func (_e *MockPairOfUserAndGroupRepository_Expecter) FindUserGroupsByUserID(ctx interface{}, operator interface{}, userID interface{}) *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call {
	return &MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call{Call: _e.mock.On("FindUserGroupsByUserID", ctx, operator, userID)}
}

func (_c *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, userID *domain.UserID)) *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 *domain.UserID
		if args[2] != nil {
			arg2 = args[2].(*domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call) Return(userGroups []*domain.UserGroup, err error) *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call {
	_c.Call.Return(userGroups, err)
	return _c
}

func (_c *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, userID *domain.UserID) ([]*domain.UserGroup, error)) *MockPairOfUserAndGroupRepository_FindUserGroupsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRBACEnforcer creates a new instance of MockRBACEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRBACEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRBACEnforcer {
	mock := &MockRBACEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRBACEnforcer is an autogenerated mock type for the RBACEnforcer type
type MockRBACEnforcer struct {
	mock.Mock
}

type MockRBACEnforcer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRBACEnforcer) EXPECT() *MockRBACEnforcer_Expecter {
	return &MockRBACEnforcer_Expecter{mock: &_m.Mock}
}

// Enforce provides a mock function for the type MockRBACEnforcer
func (_mock *MockRBACEnforcer) Enforce(rvals ...any) (bool, error) {
	var tmpRet mock.Arguments
	if len(rvals) > 0 {
		tmpRet = _mock.Called(rvals)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Enforce")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...any) (bool, error)); ok {
		return returnFunc(rvals...)
	}
	if returnFunc, ok := ret.Get(0).(func(...any) bool); ok {
		r0 = returnFunc(rvals...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(...any) error); ok {
		r1 = returnFunc(rvals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRBACEnforcer_Enforce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enforce'
type MockRBACEnforcer_Enforce_Call struct {
	*mock.Call
}

// Enforce is a helper method to define mock.On call
//   - rvals ...any
func (_e *MockRBACEnforcer_Expecter) Enforce(rvals ...interface{}) *MockRBACEnforcer_Enforce_Call {
	return &MockRBACEnforcer_Enforce_Call{Call: _e.mock.On("Enforce",
		append([]interface{}{}, rvals...)...)}
}

func (_c *MockRBACEnforcer_Enforce_Call) Run(run func(rvals ...any)) *MockRBACEnforcer_Enforce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockRBACEnforcer_Enforce_Call) Return(b bool, err error) *MockRBACEnforcer_Enforce_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRBACEnforcer_Enforce_Call) RunAndReturn(run func(rvals ...any) (bool, error)) *MockRBACEnforcer_Enforce_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPolicy provides a mock function for the type MockRBACEnforcer
func (_mock *MockRBACEnforcer) LoadPolicy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRBACEnforcer_LoadPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPolicy'
type MockRBACEnforcer_LoadPolicy_Call struct {
	*mock.Call
}

// LoadPolicy is a helper method to define mock.On call
func (_e *MockRBACEnforcer_Expecter) LoadPolicy() *MockRBACEnforcer_LoadPolicy_Call {
	return &MockRBACEnforcer_LoadPolicy_Call{Call: _e.mock.On("LoadPolicy")}
}

func (_c *MockRBACEnforcer_LoadPolicy_Call) Run(run func()) *MockRBACEnforcer_LoadPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRBACEnforcer_LoadPolicy_Call) Return(err error) *MockRBACEnforcer_LoadPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRBACEnforcer_LoadPolicy_Call) RunAndReturn(run func() error) *MockRBACEnforcer_LoadPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpacemanagerGetPersonalSpaceInterface creates a new instance of MockSpacemanagerGetPersonalSpaceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpacemanagerGetPersonalSpaceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpacemanagerGetPersonalSpaceInterface {
	mock := &MockSpacemanagerGetPersonalSpaceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpacemanagerGetPersonalSpaceInterface is an autogenerated mock type for the SpacemanagerGetPersonalSpaceInterface type
type MockSpacemanagerGetPersonalSpaceInterface struct {
	mock.Mock
}

type MockSpacemanagerGetPersonalSpaceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpacemanagerGetPersonalSpaceInterface) EXPECT() *MockSpacemanagerGetPersonalSpaceInterface_Expecter {
	return &MockSpacemanagerGetPersonalSpaceInterface_Expecter{mock: &_m.Mock}
}

// GetPersonalSpace provides a mock function for the type MockSpacemanagerGetPersonalSpaceInterface
func (_mock *MockSpacemanagerGetPersonalSpaceInterface) GetPersonalSpace(ctx context.Context, operator domain.UserInterface) (*domain.Space, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalSpace")
	}

	var r0 *domain.Space
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.Space, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.Space); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Space)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalSpace'
type MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call struct {
	*mock.Call
}

// GetPersonalSpace is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockSpacemanagerGetPersonalSpaceInterface_Expecter) GetPersonalSpace(ctx interface{}, operator interface{}) *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call {
	return &MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call{Call: _e.mock.On("GetPersonalSpace", ctx, operator)}
}

func (_c *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call) Return(space *domain.Space, err error) *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call {
	_c.Call.Return(space, err)
	return _c
}

func (_c *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.Space, error)) *MockSpacemanagerGetPersonalSpaceInterface_GetPersonalSpace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserGroupRepository creates a new instance of MockUserGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserGroupRepository {
	mock := &MockUserGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserGroupRepository is an autogenerated mock type for the UserGroupRepository type
type MockUserGroupRepository struct {
	mock.Mock
}

type MockUserGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserGroupRepository) EXPECT() *MockUserGroupRepository_Expecter {
	return &MockUserGroupRepository_Expecter{mock: &_m.Mock}
}

// AddUserGroup provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) AddUserGroup(ctx context.Context, operator domain.OwnerInterface, parameter *service.AddUserGroupParameter) (*domain.UserGroupID, error) {
	ret := _mock.Called(ctx, operator, parameter)

	if len(ret) == 0 {
		panic("no return value specified for AddUserGroup")
	}

	var r0 *domain.UserGroupID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OwnerInterface, *service.AddUserGroupParameter) (*domain.UserGroupID, error)); ok {
		return returnFunc(ctx, operator, parameter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OwnerInterface, *service.AddUserGroupParameter) *domain.UserGroupID); ok {
		r0 = returnFunc(ctx, operator, parameter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroupID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OwnerInterface, *service.AddUserGroupParameter) error); ok {
		r1 = returnFunc(ctx, operator, parameter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_AddUserGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserGroup'
type MockUserGroupRepository_AddUserGroup_Call struct {
	*mock.Call
}

// AddUserGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.OwnerInterface
//   - parameter *service.AddUserGroupParameter
func (_e *MockUserGroupRepository_Expecter) AddUserGroup(ctx interface{}, operator interface{}, parameter interface{}) *MockUserGroupRepository_AddUserGroup_Call {
	return &MockUserGroupRepository_AddUserGroup_Call{Call: _e.mock.On("AddUserGroup", ctx, operator, parameter)}
}

func (_c *MockUserGroupRepository_AddUserGroup_Call) Run(run func(ctx context.Context, operator domain.OwnerInterface, parameter *service.AddUserGroupParameter)) *MockUserGroupRepository_AddUserGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.OwnerInterface)
		}
		var arg2 *service.AddUserGroupParameter
		if args[2] != nil {
			arg2 = args[2].(*service.AddUserGroupParameter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_AddUserGroup_Call) Return(userGroupID *domain.UserGroupID, err error) *MockUserGroupRepository_AddUserGroup_Call {
	_c.Call.Return(userGroupID, err)
	return _c
}

func (_c *MockUserGroupRepository_AddUserGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.OwnerInterface, parameter *service.AddUserGroupParameter) (*domain.UserGroupID, error)) *MockUserGroupRepository_AddUserGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOwnerGroup provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) CreateOwnerGroup(ctx context.Context, operator domain.SystemOwnerInterface, organizationID *domain.OrganizationID) (*domain.UserGroupID, error) {
	ret := _mock.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOwnerGroup")
	}

	var r0 *domain.UserGroupID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, *domain.OrganizationID) (*domain.UserGroupID, error)); ok {
		return returnFunc(ctx, operator, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, *domain.OrganizationID) *domain.UserGroupID); ok {
		r0 = returnFunc(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroupID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, *domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_CreateOwnerGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOwnerGroup'
type MockUserGroupRepository_CreateOwnerGroup_Call struct {
	*mock.Call
}

// CreateOwnerGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserGroupRepository_Expecter) CreateOwnerGroup(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserGroupRepository_CreateOwnerGroup_Call {
	return &MockUserGroupRepository_CreateOwnerGroup_Call{Call: _e.mock.On("CreateOwnerGroup", ctx, operator, organizationID)}
}

func (_c *MockUserGroupRepository_CreateOwnerGroup_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, organizationID *domain.OrganizationID)) *MockUserGroupRepository_CreateOwnerGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_CreateOwnerGroup_Call) Return(userGroupID *domain.UserGroupID, err error) *MockUserGroupRepository_CreateOwnerGroup_Call {
	_c.Call.Return(userGroupID, err)
	return _c
}

func (_c *MockUserGroupRepository_CreateOwnerGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, organizationID *domain.OrganizationID) (*domain.UserGroupID, error)) *MockUserGroupRepository_CreateOwnerGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePublicGroup provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) CreatePublicGroup(ctx context.Context, operator domain.SystemOwnerInterface, organizationID *domain.OrganizationID) (*domain.UserGroupID, error) {
	ret := _mock.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePublicGroup")
	}

	var r0 *domain.UserGroupID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, *domain.OrganizationID) (*domain.UserGroupID, error)); ok {
		return returnFunc(ctx, operator, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, *domain.OrganizationID) *domain.UserGroupID); ok {
		r0 = returnFunc(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroupID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, *domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_CreatePublicGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePublicGroup'
type MockUserGroupRepository_CreatePublicGroup_Call struct {
	*mock.Call
}

// CreatePublicGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserGroupRepository_Expecter) CreatePublicGroup(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserGroupRepository_CreatePublicGroup_Call {
	return &MockUserGroupRepository_CreatePublicGroup_Call{Call: _e.mock.On("CreatePublicGroup", ctx, operator, organizationID)}
}

func (_c *MockUserGroupRepository_CreatePublicGroup_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, organizationID *domain.OrganizationID)) *MockUserGroupRepository_CreatePublicGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_CreatePublicGroup_Call) Return(userGroupID *domain.UserGroupID, err error) *MockUserGroupRepository_CreatePublicGroup_Call {
	_c.Call.Return(userGroupID, err)
	return _c
}

func (_c *MockUserGroupRepository_CreatePublicGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, organizationID *domain.OrganizationID) (*domain.UserGroupID, error)) *MockUserGroupRepository_CreatePublicGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSystemOwnerGroup provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) CreateSystemOwnerGroup(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserGroupID, error) {
	ret := _mock.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSystemOwnerGroup")
	}

	var r0 *domain.UserGroupID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.UserGroupID, error)); ok {
		return returnFunc(ctx, operator, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) *domain.UserGroupID); ok {
		r0 = returnFunc(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroupID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_CreateSystemOwnerGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystemOwnerGroup'
type MockUserGroupRepository_CreateSystemOwnerGroup_Call struct {
	*mock.Call
}

// CreateSystemOwnerGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserGroupRepository_Expecter) CreateSystemOwnerGroup(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserGroupRepository_CreateSystemOwnerGroup_Call {
	return &MockUserGroupRepository_CreateSystemOwnerGroup_Call{Call: _e.mock.On("CreateSystemOwnerGroup", ctx, operator, organizationID)}
}

func (_c *MockUserGroupRepository_CreateSystemOwnerGroup_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID)) *MockUserGroupRepository_CreateSystemOwnerGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_CreateSystemOwnerGroup_Call) Return(userGroupID *domain.UserGroupID, err error) *MockUserGroupRepository_CreateSystemOwnerGroup_Call {
	_c.Call.Return(userGroupID, err)
	return _c
}

func (_c *MockUserGroupRepository_CreateSystemOwnerGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserGroupID, error)) *MockUserGroupRepository_CreateSystemOwnerGroup_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllUserGroups provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) FindAllUserGroups(ctx context.Context, operator domain.UserInterface) ([]*domain.UserGroup, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for FindAllUserGroups")
	}

	var r0 []*domain.UserGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) ([]*domain.UserGroup, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) []*domain.UserGroup); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_FindAllUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllUserGroups'
type MockUserGroupRepository_FindAllUserGroups_Call struct {
	*mock.Call
}

// FindAllUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockUserGroupRepository_Expecter) FindAllUserGroups(ctx interface{}, operator interface{}) *MockUserGroupRepository_FindAllUserGroups_Call {
	return &MockUserGroupRepository_FindAllUserGroups_Call{Call: _e.mock.On("FindAllUserGroups", ctx, operator)}
}

func (_c *MockUserGroupRepository_FindAllUserGroups_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockUserGroupRepository_FindAllUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_FindAllUserGroups_Call) Return(userGroups []*domain.UserGroup, err error) *MockUserGroupRepository_FindAllUserGroups_Call {
	_c.Call.Return(userGroups, err)
	return _c
}

func (_c *MockUserGroupRepository_FindAllUserGroups_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) ([]*domain.UserGroup, error)) *MockUserGroupRepository_FindAllUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// FindSystemOwnerGroup provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) FindSystemOwnerGroup(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserGroup, error) {
	ret := _mock.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerGroup")
	}

	var r0 *domain.UserGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.UserGroup, error)); ok {
		return returnFunc(ctx, operator, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) *domain.UserGroup); ok {
		r0 = returnFunc(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_FindSystemOwnerGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerGroup'
type MockUserGroupRepository_FindSystemOwnerGroup_Call struct {
	*mock.Call
}

// FindSystemOwnerGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserGroupRepository_Expecter) FindSystemOwnerGroup(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserGroupRepository_FindSystemOwnerGroup_Call {
	return &MockUserGroupRepository_FindSystemOwnerGroup_Call{Call: _e.mock.On("FindSystemOwnerGroup", ctx, operator, organizationID)}
}

func (_c *MockUserGroupRepository_FindSystemOwnerGroup_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID)) *MockUserGroupRepository_FindSystemOwnerGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_FindSystemOwnerGroup_Call) Return(userGroup *domain.UserGroup, err error) *MockUserGroupRepository_FindSystemOwnerGroup_Call {
	_c.Call.Return(userGroup, err)
	return _c
}

func (_c *MockUserGroupRepository_FindSystemOwnerGroup_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserGroup, error)) *MockUserGroupRepository_FindSystemOwnerGroup_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserGroupByID provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) FindUserGroupByID(ctx context.Context, operator domain.UserInterface, userGroupID *domain.UserGroupID) (*domain.UserGroup, error) {
	ret := _mock.Called(ctx, operator, userGroupID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserGroupByID")
	}

	var r0 *domain.UserGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserGroupID) (*domain.UserGroup, error)); ok {
		return returnFunc(ctx, operator, userGroupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, *domain.UserGroupID) *domain.UserGroup); ok {
		r0 = returnFunc(ctx, operator, userGroupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, *domain.UserGroupID) error); ok {
		r1 = returnFunc(ctx, operator, userGroupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_FindUserGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserGroupByID'
type MockUserGroupRepository_FindUserGroupByID_Call struct {
	*mock.Call
}

// FindUserGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - userGroupID *domain.UserGroupID
func (_e *MockUserGroupRepository_Expecter) FindUserGroupByID(ctx interface{}, operator interface{}, userGroupID interface{}) *MockUserGroupRepository_FindUserGroupByID_Call {
	return &MockUserGroupRepository_FindUserGroupByID_Call{Call: _e.mock.On("FindUserGroupByID", ctx, operator, userGroupID)}
}

func (_c *MockUserGroupRepository_FindUserGroupByID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, userGroupID *domain.UserGroupID)) *MockUserGroupRepository_FindUserGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 *domain.UserGroupID
		if args[2] != nil {
			arg2 = args[2].(*domain.UserGroupID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_FindUserGroupByID_Call) Return(userGroup *domain.UserGroup, err error) *MockUserGroupRepository_FindUserGroupByID_Call {
	_c.Call.Return(userGroup, err)
	return _c
}

func (_c *MockUserGroupRepository_FindUserGroupByID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, userGroupID *domain.UserGroupID) (*domain.UserGroup, error)) *MockUserGroupRepository_FindUserGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserGroupByKey provides a mock function for the type MockUserGroupRepository
func (_mock *MockUserGroupRepository) FindUserGroupByKey(ctx context.Context, operator domain.UserInterface, key string) (*domain.UserGroup, error) {
	ret := _mock.Called(ctx, operator, key)

	if len(ret) == 0 {
		panic("no return value specified for FindUserGroupByKey")
	}

	var r0 *domain.UserGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.UserGroup, error)); ok {
		return returnFunc(ctx, operator, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.UserGroup); ok {
		r0 = returnFunc(ctx, operator, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGroupRepository_FindUserGroupByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserGroupByKey'
type MockUserGroupRepository_FindUserGroupByKey_Call struct {
	*mock.Call
}

// FindUserGroupByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - key string
func (_e *MockUserGroupRepository_Expecter) FindUserGroupByKey(ctx interface{}, operator interface{}, key interface{}) *MockUserGroupRepository_FindUserGroupByKey_Call {
	return &MockUserGroupRepository_FindUserGroupByKey_Call{Call: _e.mock.On("FindUserGroupByKey", ctx, operator, key)}
}

func (_c *MockUserGroupRepository_FindUserGroupByKey_Call) Run(run func(ctx context.Context, operator domain.UserInterface, key string)) *MockUserGroupRepository_FindUserGroupByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserGroupRepository_FindUserGroupByKey_Call) Return(userGroup *domain.UserGroup, err error) *MockUserGroupRepository_FindUserGroupByKey_Call {
	_c.Call.Return(userGroup, err)
	return _c
}

func (_c *MockUserGroupRepository_FindUserGroupByKey_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, key string) (*domain.UserGroup, error)) *MockUserGroupRepository_FindUserGroupByKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryFindSystemOwnerByOrganizationName creates a new instance of MockUserRepositoryFindSystemOwnerByOrganizationName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryFindSystemOwnerByOrganizationName(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryFindSystemOwnerByOrganizationName {
	mock := &MockUserRepositoryFindSystemOwnerByOrganizationName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryFindSystemOwnerByOrganizationName is an autogenerated mock type for the UserRepositoryFindSystemOwnerByOrganizationName type
type MockUserRepositoryFindSystemOwnerByOrganizationName struct {
	mock.Mock
}

type MockUserRepositoryFindSystemOwnerByOrganizationName_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryFindSystemOwnerByOrganizationName) EXPECT() *MockUserRepositoryFindSystemOwnerByOrganizationName_Expecter {
	return &MockUserRepositoryFindSystemOwnerByOrganizationName_Expecter{mock: &_m.Mock}
}

// FindSystemOwnerByOrganizationName provides a mock function for the type MockUserRepositoryFindSystemOwnerByOrganizationName
func (_mock *MockUserRepositoryFindSystemOwnerByOrganizationName) FindSystemOwnerByOrganizationName(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error) {
	ret := _mock.Called(ctx, operator, organizationName)

	if len(ret) == 0 {
		panic("no return value specified for FindSystemOwnerByOrganizationName")
	}

	var r0 *domain.SystemOwner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) (*domain.SystemOwner, error)); ok {
		return returnFunc(ctx, operator, organizationName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, string) *domain.SystemOwner); ok {
		r0 = returnFunc(ctx, operator, organizationName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SystemOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, organizationName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSystemOwnerByOrganizationName'
type MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call struct {
	*mock.Call
}

// FindSystemOwnerByOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationName string
func (_e *MockUserRepositoryFindSystemOwnerByOrganizationName_Expecter) FindSystemOwnerByOrganizationName(ctx interface{}, operator interface{}, organizationName interface{}) *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call {
	return &MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call{Call: _e.mock.On("FindSystemOwnerByOrganizationName", ctx, operator, organizationName)}
}

func (_c *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string)) *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call) Return(systemOwner *domain.SystemOwner, err error) *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(systemOwner, err)
	return _c
}

func (_c *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationName string) (*domain.SystemOwner, error)) *MockUserRepositoryFindSystemOwnerByOrganizationName_FindSystemOwnerByOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryFindUserByLoginID creates a new instance of MockUserRepositoryFindUserByLoginID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryFindUserByLoginID(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryFindUserByLoginID {
	mock := &MockUserRepositoryFindUserByLoginID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryFindUserByLoginID is an autogenerated mock type for the UserRepositoryFindUserByLoginID type
type MockUserRepositoryFindUserByLoginID struct {
	mock.Mock
}

type MockUserRepositoryFindUserByLoginID_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryFindUserByLoginID) EXPECT() *MockUserRepositoryFindUserByLoginID_Expecter {
	return &MockUserRepositoryFindUserByLoginID_Expecter{mock: &_m.Mock}
}

// FindUserByLoginID provides a mock function for the type MockUserRepositoryFindUserByLoginID
func (_mock *MockUserRepositoryFindUserByLoginID) FindUserByLoginID(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error) {
	ret := _mock.Called(ctx, operator, loginID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByLoginID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) (*domain.User, error)); ok {
		return returnFunc(ctx, operator, loginID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface, string) *domain.User); ok {
		r0 = returnFunc(ctx, operator, loginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByLoginID'
type MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call struct {
	*mock.Call
}

// FindUserByLoginID is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
//   - loginID string
func (_e *MockUserRepositoryFindUserByLoginID_Expecter) FindUserByLoginID(ctx interface{}, operator interface{}, loginID interface{}) *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call {
	return &MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call{Call: _e.mock.On("FindUserByLoginID", ctx, operator, loginID)}
}

func (_c *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call) Run(run func(ctx context.Context, operator domain.UserInterface, loginID string)) *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call) Return(user *domain.User, err error) *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface, loginID string) (*domain.User, error)) *MockUserRepositoryFindUserByLoginID_FindUserByLoginID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryVerifyPassword creates a new instance of MockUserRepositoryVerifyPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryVerifyPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryVerifyPassword {
	mock := &MockUserRepositoryVerifyPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryVerifyPassword is an autogenerated mock type for the UserRepositoryVerifyPassword type
type MockUserRepositoryVerifyPassword struct {
	mock.Mock
}

type MockUserRepositoryVerifyPassword_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryVerifyPassword) EXPECT() *MockUserRepositoryVerifyPassword_Expecter {
	return &MockUserRepositoryVerifyPassword_Expecter{mock: &_m.Mock}
}

// VerifyPassword provides a mock function for the type MockUserRepositoryVerifyPassword
func (_mock *MockUserRepositoryVerifyPassword) VerifyPassword(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error) {
	ret := _mock.Called(ctx, operator, loginID, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) (bool, error)); ok {
		return returnFunc(ctx, operator, loginID, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerInterface, string, string) bool); ok {
		r0 = returnFunc(ctx, operator, loginID, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemOwnerInterface, string, string) error); ok {
		r1 = returnFunc(ctx, operator, loginID, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryVerifyPassword_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockUserRepositoryVerifyPassword_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemOwnerInterface
//   - loginID string
//   - password string
func (_e *MockUserRepositoryVerifyPassword_Expecter) VerifyPassword(ctx interface{}, operator interface{}, loginID interface{}, password interface{}) *MockUserRepositoryVerifyPassword_VerifyPassword_Call {
	return &MockUserRepositoryVerifyPassword_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", ctx, operator, loginID, password)}
}

func (_c *MockUserRepositoryVerifyPassword_VerifyPassword_Call) Run(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string)) *MockUserRepositoryVerifyPassword_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemOwnerInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemOwnerInterface)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepositoryVerifyPassword_VerifyPassword_Call) Return(b bool, err error) *MockUserRepositoryVerifyPassword_VerifyPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepositoryVerifyPassword_VerifyPassword_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemOwnerInterface, loginID string, password string) (bool, error)) *MockUserRepositoryVerifyPassword_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryGetUser creates a new instance of MockUserRepositoryGetUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryGetUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryGetUser {
	mock := &MockUserRepositoryGetUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryGetUser is an autogenerated mock type for the UserRepositoryGetUser type
type MockUserRepositoryGetUser struct {
	mock.Mock
}

type MockUserRepositoryGetUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryGetUser) EXPECT() *MockUserRepositoryGetUser_Expecter {
	return &MockUserRepositoryGetUser_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUserRepositoryGetUser
func (_mock *MockUserRepositoryGetUser) GetUser(ctx context.Context, operator domain.UserInterface) (*domain.User, error) {
	ret := _mock.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) (*domain.User, error)); ok {
		return returnFunc(ctx, operator)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserInterface) *domain.User); ok {
		r0 = returnFunc(ctx, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserInterface) error); ok {
		r1 = returnFunc(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryGetUser_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepositoryGetUser_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.UserInterface
func (_e *MockUserRepositoryGetUser_Expecter) GetUser(ctx interface{}, operator interface{}) *MockUserRepositoryGetUser_GetUser_Call {
	return &MockUserRepositoryGetUser_GetUser_Call{Call: _e.mock.On("GetUser", ctx, operator)}
}

func (_c *MockUserRepositoryGetUser_GetUser_Call) Run(run func(ctx context.Context, operator domain.UserInterface)) *MockUserRepositoryGetUser_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserInterface
		if args[1] != nil {
			arg1 = args[1].(domain.UserInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryGetUser_GetUser_Call) Return(user *domain.User, err error) *MockUserRepositoryGetUser_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryGetUser_GetUser_Call) RunAndReturn(run func(ctx context.Context, operator domain.UserInterface) (*domain.User, error)) *MockUserRepositoryGetUser_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryCreateSystemOwner creates a new instance of MockUserRepositoryCreateSystemOwner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryCreateSystemOwner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryCreateSystemOwner {
	mock := &MockUserRepositoryCreateSystemOwner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryCreateSystemOwner is an autogenerated mock type for the UserRepositoryCreateSystemOwner type
type MockUserRepositoryCreateSystemOwner struct {
	mock.Mock
}

type MockUserRepositoryCreateSystemOwner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryCreateSystemOwner) EXPECT() *MockUserRepositoryCreateSystemOwner_Expecter {
	return &MockUserRepositoryCreateSystemOwner_Expecter{mock: &_m.Mock}
}

// CreateSystemOwner provides a mock function for the type MockUserRepositoryCreateSystemOwner
func (_mock *MockUserRepositoryCreateSystemOwner) CreateSystemOwner(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserID, error) {
	ret := _mock.Called(ctx, operator, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSystemOwner")
	}

	var r0 *domain.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) (*domain.UserID, error)); ok {
		return returnFunc(ctx, operator, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) *domain.UserID); ok {
		r0 = returnFunc(ctx, operator, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SystemAdminInterface, *domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, operator, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystemOwner'
type MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call struct {
	*mock.Call
}

// CreateSystemOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - operator domain.SystemAdminInterface
//   - organizationID *domain.OrganizationID
func (_e *MockUserRepositoryCreateSystemOwner_Expecter) CreateSystemOwner(ctx interface{}, operator interface{}, organizationID interface{}) *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call {
	return &MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call{Call: _e.mock.On("CreateSystemOwner", ctx, operator, organizationID)}
}

func (_c *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call) Run(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID)) *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SystemAdminInterface
		if args[1] != nil {
			arg1 = args[1].(domain.SystemAdminInterface)
		}
		var arg2 *domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(*domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call) Return(userID *domain.UserID, err error) *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call) RunAndReturn(run func(ctx context.Context, operator domain.SystemAdminInterface, organizationID *domain.OrganizationID) (*domain.UserID, error)) *MockUserRepositoryCreateSystemOwner_CreateSystemOwner_Call {
	_c.Call.Return(run)
	return _c
}
